# Config file for generating atk data for text encoder inference

atker_pms:
    length: 32
    chars: "abcdefghijklmnopqrstuvwxyz1234567890!?.,!@#$%^&*()-=+"
    beam_k1: 64
    beam_k2: 32

gen_num: 20
query_bs: 2000
