atkdata:
    - "./results/exp-text/atk/bertlarge/1/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/2/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/3/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/4/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/5/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/6/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/7/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/8/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/9/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/10/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/11/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/12/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/13/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/14/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/15/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/16/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/17/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/18/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/19/atk_gen-data.pkl"
    - "./results/exp-text/atk/bertlarge/20/atk_gen-data.pkl"
